version: "3.7"
services:
  gateway-service:
    image: openjdk:11
    volumes:
      - ./build/libs:/app
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "
        -Dspring.profiles.active=dev
      "
    command: java -jar /app/gateway-0.0.1-SNAPSHOT.jar
    networks:
      - my_network


networks:
  my_network:
    external:
      name: my_network